# Information about this book

# The book's main title
title: "The Park"

# The subtitle, if any
subtitle: ""

# The author
creator: "Gail Schimmel"

# Other contributors
contributor: ""

# The book's blurb
description: |


# A image representing the book,
# usually the front cover.
image: "cover.jpg"

# Publisher, imprint or brand name
publisher: "Macmillan"

# Publisher's website
publisher-url: ""

# Who owns the copyright?
rightsholder: "Gail Schimmel"

# A copyright statement or licence wording
rights: |
  All rights reserved. No part of this publication may be reproduced, stored in or introduced into a retrieval system, or transmitted, in any form or by any means (electronic, mechanical, photocopying, recording or otherwise), without the prior written permission of the publisher. Any person who does any unauthorised act in relation to this publication may be liable to criminal prosecution and civil claims for damages.

# Language code
# Use ISO 639-1, 639-2, or 639-3 codes
# (in that order of preference)
language: "en"

# Official, original publication date
# YYYY-MM-DD
date: "2017"

# Date of last revision
# YYYY-MM-DD
modified: ""

# Book type, e.g. Novel, Poetry, Memoir
type: "Novel"

# Subject areas
# E.g. BISAC: https://bisg.org/page/BISACEdition
#      BIC: https://ns.editeur.org/bic_categories
subject: ""

# ISBN or UUID
identifier: "978-1-77010-515-7"

# Parent work's ISBN or ISTC
# if this is a derivative work.
source: ""

# ISBN or ISTC of a related work
relation: ""

# Any specific place or time this book is about?
# E.g. geographic place or chronological time span
coverage: ""

# Keywords that describe this project, comma-separated.
# Used, for example, in PDF metadata.
keywords: ""

# Details about each product of this work
products:

  # Details about the print version of this work
  print-pdf:

    # Format
    # e.g. Paperback, Digital download, Digital online
    format: "Print"
    files:
      - "0-1-halftitlepage"
      - "0-2-previous-publications"
      - "0-3-titlepage"
      - "0-4-copyright"
      - "0-5-dedication"
      - "0-6-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "50-1-acknowledgements"

  # Details about the website version of this work
  web:

    # Format
    # e.g. Paperback, Digital download, Digital online
    format: "Online" # e.g. Paperback, Digital download, Digital online
    files:
      - "0-0-cover"
      - "0-1-halftitlepage"
      - "0-2-previous-publications"
      - "0-3-titlepage"
      - "0-4-copyright"
      - "0-5-dedication"
      - "0-6-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "50-1-acknowledgements"

  # Details about the epub version of this work
  epub:

    # Format
    # e.g. Paperback, Digital download, Digital online
    format: "Ebook" # e.g. Paperback, Digital download, Digital online
    identifier: "978-1-77010-516-4"
    files:
      - "0-0-cover"
      - "0-1-halftitlepage"
      - "0-2-previous-publications"
      - "0-3-titlepage"
      - "0-4-copyright"
      - "0-5-dedication"
      - "0-6-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "50-1-acknowledgements"

  # Details about the screen-PDF version of this work
  screen-pdf:

    # Format
    # e.g. Paperback, Digital download, Digital online
    format: "PDF" # e.g. Paperback, Digital download, Digital online
    files:
      - "0-0-cover"
      - "0-1-halftitlepage"
      - "0-2-previous-publications"
      - "0-3-titlepage"
      - "0-4-copyright"
      - "0-5-dedication"
      - "0-6-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "50-1-acknowledgements"

  # Details about the app version of this work
  app:

    # Format
    # e.g. Paperback, Digital download, Digital online
    format: "App" # e.g. Paperback, Digital download, Digital online
    files:
      - "0-0-cover"
      - "0-1-halftitlepage"
      - "0-2-previous-publications"
      - "0-3-titlepage"
      - "0-4-copyright"
      - "0-5-dedication"
      - "0-6-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "50-1-acknowledgements"
